/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Kq6D5Dhbuvy
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Button } from "@/components/ui/button"
import { Collapsible, CollapsibleTrigger, CollapsibleContent } from "@/components/ui/collapsible"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import Link from "next/link"
import Image from "next/image"

export function LandingPage() {
  return (
    <div className="w-full">
      <header className="flex items-center justify-between p-4 bg-white shadow-md">
        <div className="flex items-center">
        <Image
            src="/logo.png"
            alt="Coneduc Logo"
            className="h-8"
          />
        </div>
        <Button variant="outline">Contact us</Button>
      </header>
      <section className="flex flex-col items-center justify-center py-16 bg-gradient-to-r from-blue-500 to-blue-700 text-white">
        <div className="text-center max-w-2xl">
          <h1 className="text-4xl font-bold">Empower Your Expertise: Teach, Consult, and Grow Your Business</h1>
          <p className="mt-4 text-lg">
          The all-in-one platform for trainers, experts, and training schools to manage and sell their educational services.
          </p>
          <Button className="mt-6 bg-blue-500 hover:bg-blue-600 text-white">Schedule a Demo</Button>
        </div>
      </section>
      <section className="p-8">
        <h2 className="text-3xl font-bold text-center">For Teaching</h2>
        <div className="mx-auto max-w-4xl mt-8">
          <Image
            src="/teaching.png"
            width={1280}
            height={720}
            alt="Teaching"
            className="w-full rounded-lg"
            style={{ aspectRatio: "1280/720", objectFit: "cover" }}
          />
        </div>
        <div className="grid grid-cols-1 gap-8 mt-8 md:grid-cols-2 lg:grid-cols-4">
          <div className="bg-card text-card-foreground shadow-md hover:shadow-lg transition-shadow">
            <div className="p-4">
              <RocketIcon className="w-12 h-12 text-primary" />
              <h3 className="text-xl font-semibold mt-4">Create Your Online Academy</h3>
              <p className="mt-2 text-muted-foreground">
                Transform your teaching into a thriving business by establishing your online academy. Our platform
                ensures scalability, connecting you with an unlimited pool of students.
              </p>
            </div>
          </div>
          <div className="bg-card text-card-foreground shadow-md hover:shadow-lg transition-shadow">
            <div className="p-4">
              <BookIcon className="w-12 h-12 text-primary" />
              <h3 className="text-xl font-semibold mt-4">Manage Your Courses</h3>
              <p className="mt-2 text-muted-foreground">
                Our user-friendly platform simplifies the process of sharing your courses swiftly. It also offers tools
                to aid in course management and facilitate interaction with your students.
              </p>
            </div>
          </div>
          <div className="bg-card text-card-foreground shadow-md hover:shadow-lg transition-shadow">
            <div className="p-4">
              <UsersIcon className="w-12 h-12 text-primary" />
              <h3 className="text-xl font-semibold mt-4">Manage Your Students</h3>
              <p className="mt-2 text-muted-foreground">
                Effortlessly oversee your students&apos; progress and engagement. Our AI-powered tools streamline
                communication, grading, and administrative tasks, so you can focus on teaching.
              </p>
            </div>
          </div>
          <div className="bg-card text-card-foreground shadow-md hover:shadow-lg transition-shadow">
            <div className="p-4">
              <BarChartIcon className="w-12 h-12 text-primary" />
              <h3 className="text-xl font-semibold mt-4">Valuable Insights</h3>
              <p className="mt-2 text-muted-foreground">
                Unlock the power of data analytics to gain valuable insights into your academy&apos;s performance and the
                effectiveness of your courses. Our platform provides comprehensive analytics tools.
              </p>
            </div>
          </div>
        </div>
      </section>
      <section className="p-8">
        <h2 className="text-3xl font-bold text-center">For Learning</h2>
        <div className="grid grid-cols-1 gap-8 mt-8 md:grid-cols-2 lg:grid-cols-4 justify-items-center">
          <div className="bg-card text-card-foreground shadow-md hover:shadow-lg transition-shadow">
            <Image
              src="/explore.png"
              width={300}
              height={450}
              alt="Explore page screenshot"
            className="w-full rounded-lg object-top"
            style={{ aspectRatio: "300/400", objectFit: "cover", objectPosition: "top" }}
            />
            <div className="p-4">
              <SearchIcon className="w-12 h-12 text-primary" />
              <h3 className="text-xl font-semibold mt-4">Explore Courses</h3>
              <p className="mt-2 text-muted-foreground">
                Discover a diverse range of courses taught by passionate educators from around the world. From academic
                subjects to practical skills, there&apos;s something for everyone.
              </p>
            </div>
          </div>
          <div className="bg-card text-card-foreground shadow-md hover:shadow-lg transition-shadow">
          <Image
            src="/learning.png"
            width={300}
            height={450}
            alt="Learning page Screenshot"
            className="w-full rounded-lg object-top"
            style={{ aspectRatio: "300/400", objectFit: "cover", objectPosition: "top" }}
          />
            <div className="p-4">
              <CompassIcon className="w-12 h-12 text-primary" />
              <h3 className="text-xl font-semibold mt-4">Great Learning Experience</h3>
              <p className="mt-2 text-muted-foreground">
                Experience learning like never before. Our platform utilizes cutting-edge technologies and best
                practices to personalize your learning journey, ensuring maximum engagement and comprehension.
              </p>
            </div>
          </div>
          <div className="bg-card text-card-foreground shadow-md hover:shadow-lg transition-shadow">
            <Image
              src="/practice.png"
              width={300}
              height={450}
              alt="Practice tab Screenshot"
            className="w-full rounded-lg object-top"
            style={{ aspectRatio: "300/400", objectFit: "cover", objectPosition: "top" }}
            />
            <div className="p-4">
              <CircleHelpIcon className="w-12 h-12 text-primary" />
              <h3 className="text-xl font-semibold mt-4">Practice and Ask for Help</h3>
              <p className="mt-2 text-muted-foreground">
                Master new concepts with interactive exercises. Need clarification or guidance? Our community of
                instructors and fellow learners are here to support you every step of the way.
              </p>
            </div>
          </div>
          <div className="bg-card text-card-foreground shadow-md hover:shadow-lg transition-shadow">
            <Image
              src="/progress.png"
              width={300}
              height={450}
              alt="My courses Screenshot"
            className="w-full rounded-lg object-top"
            style={{ aspectRatio: "300/400", objectFit: "cover", objectPosition: "top" }}
            />
            <div className="p-4">
              <ClipboardIcon className="w-12 h-12 text-primary" />
              <h3 className="text-xl font-semibold mt-4">Track Your Progress</h3>
              <p className="mt-2 text-muted-foreground">
                Keep track of your learning journey with our comprehensive progress tracking tools. Set goals, monitor
                your achievements, and stay motivated as you advance through your courses.
              </p>
            </div>
          </div>
        </div>
      </section>
      <section className="p-8 bg-muted">
        <h2 className="text-3xl font-bold text-center">FAQ</h2>
        <ul className="mt-8 space-y-4">
          <li>
            <Collapsible>
              <CollapsibleTrigger className="flex items-center justify-between p-4 cursor-pointer">
                <h3 className="text-xl font-semibold">What is Coneduc?</h3>
                <ChevronDownIcon className="w-5 h-5 transition-transform [&[data-state=open]]:rotate-180" />
              </CollapsibleTrigger>
              <CollapsibleContent className="p-4">
                <p className="text-muted-foreground">
                  Coneduc is an efficient platform that enables schools to effortlessly share their courses, eliminating
                  the hassle of marketing and technical management.
                </p>
              </CollapsibleContent>
            </Collapsible>
          </li>
          <li>
            <Collapsible>
              <CollapsibleTrigger className="flex items-center justify-between p-4 cursor-pointer">
                <h3 className="text-xl font-semibold">How does Coneduc work?</h3>
                <ChevronDownIcon className="w-5 h-5 transition-transform [&[data-state=open]]:rotate-180" />
              </CollapsibleTrigger>
              <CollapsibleContent className="p-4">
                <p className="text-muted-foreground">
                  Coneduc provides a user-friendly platform for schools to create and manage their online courses. It
                  handles the technical aspects, allowing educators to focus on teaching.
                </p>
              </CollapsibleContent>
            </Collapsible>
          </li>
          <li>
            <Collapsible>
              <CollapsibleTrigger className="flex items-center justify-between p-4 cursor-pointer">
                <h3 className="text-xl font-semibold">What are the benefits of using Coneduc?</h3>
                <ChevronDownIcon className="w-5 h-5 transition-transform [&[data-state=open]]:rotate-180" />
              </CollapsibleTrigger>
              <CollapsibleContent className="p-4">
                <p className="text-muted-foreground">
                  Coneduc offers a range of benefits, including scalability, course management tools, student engagement
                  features, and comprehensive analytics.
                </p>
              </CollapsibleContent>
            </Collapsible>
          </li>
          <li>
            <Collapsible>
              <CollapsibleTrigger className="flex items-center justify-between p-4 cursor-pointer">
                <h3 className="text-xl font-semibold">How much does Coneduc cost?</h3>
                <ChevronDownIcon className="w-5 h-5 transition-transform [&[data-state=open]]:rotate-180" />
              </CollapsibleTrigger>
              <CollapsibleContent className="p-4">
                <p className="text-muted-foreground">
                  Coneduc offers flexible pricing plans to suit the needs of different schools and budgets. Contact us
                  for more information on our pricing options.
                </p>
              </CollapsibleContent>
            </Collapsible>
          </li>
          <li>
            <Collapsible>
              <CollapsibleTrigger className="flex items-center justify-between p-4 cursor-pointer">
                <h3 className="text-xl font-semibold">How do I get started with Coneduc?</h3>
                <ChevronDownIcon className="w-5 h-5 transition-transform [&[data-state=open]]:rotate-180" />
              </CollapsibleTrigger>
              <CollapsibleContent className="p-4">
                <p className="text-muted-foreground">
                  To get started with Coneduc, simply schedule a demo with our team. They&apos;ll guide you through the
                  platform and help you set up your online academy.
                </p>
              </CollapsibleContent>
            </Collapsible>
          </li>
          <li>
            <Collapsible>
              <CollapsibleTrigger className="flex items-center justify-between p-4 cursor-pointer">
                <h3 className="text-xl font-semibold">What kind of support does Coneduc offer?</h3>
                <ChevronDownIcon className="w-5 h-5 transition-transform [&[data-state=open]]:rotate-180" />
              </CollapsibleTrigger>
              <CollapsibleContent className="p-4">
                <p className="text-muted-foreground">
                  Coneduc provides comprehensive support, including a dedicated account manager, technical assistance,
                  and a knowledgeable customer service team.
                </p>
              </CollapsibleContent>
            </Collapsible>
          </li>
        </ul>
      </section>
      <section className="p-8">
        <h2 className="text-3xl font-bold text-center">Contact Us</h2>
        <form className="max-w-xl mx-auto mt-8 space-y-4">
          <div className="space-y-2">
            <Label htmlFor="full-name">Full Name</Label>
            <Input id="full-name" placeholder="Enter your full name" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="email">Email</Label>
            <Input id="email" placeholder="Enter your email" type="email" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="message">Message</Label>
            <Textarea id="message" placeholder="Enter your message" className="min-h-[100px]" />
          </div>
          <Button className="w-full bg-blue-500 hover:bg-blue-600 text-white">Submit</Button>
        </form>
      </section>
      <footer className="p-4 bg-white shadow-md">
        <div className="flex justify-between items-center">
          <span className="text-muted-foreground">© Coneduc 2024. All rights reserved.</span>
          <div className="flex space-x-4 text-muted-foreground">
            <Link href="#" className="hover:text-foreground" prefetch={false}>
              <FacebookIcon className="w-5 h-5" />
            </Link>
            <Link href="#" className="hover:text-foreground" prefetch={false}>
              <InstagramIcon className="w-5 h-5" />
            </Link>
            <Link href="#" className="hover:text-foreground" prefetch={false}>
              <LinkedinIcon className="w-5 h-5" />
            </Link>
            <Link href="#" className="hover:text-foreground" prefetch={false}>
              <YoutubeIcon className="w-5 h-5" />
            </Link>
          </div>
        </div>
      </footer>
    </div>
  )
}

function BarChartIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="12" x2="12" y1="20" y2="10" />
      <line x1="18" x2="18" y1="20" y2="4" />
      <line x1="6" x2="6" y1="20" y2="16" />
    </svg>
  )
}


function BookIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20" />
    </svg>
  )
}


function ChevronDownIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  )
}


function CircleHelpIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3" />
      <path d="M12 17h.01" />
    </svg>
  )
}


function ClipboardIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="8" height="4" x="8" y="2" rx="1" ry="1" />
      <path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2" />
    </svg>
  )
}


function CompassIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m16.24 7.76-1.804 5.411a2 2 0 0 1-1.265 1.265L7.76 16.24l1.804-5.411a2 2 0 0 1 1.265-1.265z" />
      <circle cx="12" cy="12" r="10" />
    </svg>
  )
}


function FacebookIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>
  )
}


function InstagramIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>
  )
}


function LinkedinIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  )
}

function YoutubeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2.5 17a24.12 24.12 0 0 1 0-10 2 2 0 0 1 1.4-1.4 49.56 49.56 0 0 1 16.2 0A2 2 0 0 1 21.5 7a24.12 24.12 0 0 1 0 10 2 2 0 0 1-1.4 1.4 49.55 49.55 0 0 1-16.2 0A2 2 0 0 1 2.5 17" />
      <path d="m10 15 5-3-5-3z" />
    </svg>
  )
}


function RocketIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4.5 16.5c-1.5 1.26-2 5-2 5s3.74-.5 5-2c.71-.84.7-2.13-.09-2.91a2.18 2.18 0 0 0-2.91-.09z" />
      <path d="m12 15-3-3a22 22 0 0 1 2-3.95A12.88 12.88 0 0 1 22 2c0 2.72-.78 7.5-6 11a22.35 22.35 0 0 1-4 2z" />
      <path d="M9 12H4s.55-3.03 2-4c1.62-1.08 5 0 5 0" />
      <path d="M12 15v5s3.03-.55 4-2c1.08-1.62 0-5 0-5" />
    </svg>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function UsersIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>
  )
}

